version: '3.1'

services:
  db:
    container_name: studentrecord-db
    image: postgres
    environment:
      POSTGRES_DB: studentrecord-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data

volumes:
  my_db_volume:
