version: '3.1'

services:
  db:
    container_name: studentrecord-db
    image: postgres
    environment:
      POSTGRES_DB: studentrecord-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my_db_volume:
    external: true
